apiVersion: batch/v1
kind: Job
metadata:
  name: buildkit
spec:
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/buildkit: unconfined
    spec:
      restartPolicy: Never
      initContainers:
        - name: prepare
          image: alpine/git
          command:
            - git
            - clone
            - http://git.solenopsys.org/alexstorm-hsm-ci
            - /workspace/alexstorm-hsm-ci
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      containers:
        - name: buildkit
          image: moby/buildkit:master-rootless
          env:
            - name: BUILDKITD_FLAGS
              value: --oci-worker-no-process-sandbox
          command:
            - buildctl-daemonless.sh
          args:
            - build
            - --frontend
            - dockerfile.v0
            - --opt
            - platform=linux/amd64,linux/arm64
            - --local
            - context=/workspace
            - --local
            - dockerfile=/workspace/alexstorm-hsm-ci/cic/jobs/test
            - --output
            - type=image,name=registry.solenopsys.org/alexstorm-hsm-ci,push=true
          volumeMounts:
            - name: workspace
              readOnly: true
              mountPath: /workspace
      volumes:
        - name: workspace
          emptyDir: {}
