apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.selectorLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullName }}
        type: hStreamNode
        hsServiceName:  {{ .Values.hsServiceName }}
    spec:
      containers:
        - name:  {{ .Values.containers.front-adapter.name}}
          image: {{ .Values.containers.front-adapter.image}}
          ports:
            - containerPort: {{ .Values.containers.front-adapter.zmqPort}}
          env:
            - name: "zmq.SocketUrl"
              value: "tcp://*:{{ .Values.containers.router.zmqPort}}"
