kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: system:serviceaccount:default:default
  name: service-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services","pods","deployments"]
  verbs: ["get", "watch", "list"]
